version: 2.1
executors:
  cci-toolbox-java11:
    docker:
      - image: eu.gcr.io/entur-system-1287/circleci-toolbox-image-java11
        auth:
          username: _json_key
          password: $DOCKER_PASSWORD
    environment:
      DEBIAN_FRONTEND: "noninteractive"
      MAVEN_OPTS: -Xmx3G
aliases:
  - &post_build
    name: Trigger downstream builds
    command: |
      echo 'export CIRCLE_SHA1="$CIRCLE_SHA1"' >> $BASH_ENV
      echo 'export CIRCLE_PROJECT_REPONAME="$CIRCLE_PROJECT_REPONAME"' >> $BASH_ENV
      /tools/trigger_build_v2.sh "entur/otp-deployment-config.git" "master" "$(git log -1 --pretty=%B)"
jobs:
  build:
    executor: cci-toolbox-java11
    steps:
      - checkout
      - restore_cache:
          key: dep-cache-{{ checksum "pom.xml" }}
      - run: mvn org.apache.maven.plugins:maven-dependency-plugin:3.1.0:go-offline -s /tools/m2/settings.xml
      - save_cache:
          paths:
            - ~/.m2
          key: dep-cache-{{ checksum "pom.xml" }}
      - run: mvn install org.apache.maven.plugins:maven-deploy-plugin:2.8.2:deploy  -s /tools/m2/settings.xml -DskipTests -Dgpg.skip -DaltDeploymentRepository=snapshots::default::https://entur2.jfrog.io/entur2/libs-snapshot-local
      - run: *post_build
workflows:
  version: 2.1
  release:
    jobs:
      - build:
          name: build-release
          context: dev
          filters:
            branches:
              only:
                - entur_raptor
                - rutebanken_develop
                - otp2_entur_develop